### ISSUE TITLE
Have a single module with synced classes from `keycloak/keycloak`

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak-client#34]
### Description

Currently classes are synced from `keycloak/keycloak` into multiple Maven modules, which then contains a mix of Java files maintained in `keycloak/keycloak` and those maintained in `keycloak/keycloak-client`.

It may be better to have a separate `client-common-synced` module or whatever that only contains synced Java files, and a README.md in the top that says don't touch, or some other ways to mention this.

**Comment by stianst** [comment]
@thomasdarimont @mposolda FIY

**Comment by mposolda** [comment]
@stianst We already have README where we mention which modules are "synced" - https://github.com/keycloak/keycloak-client/blob/main/README.md#keycloak-client

If we sync all the files just to the single module `keycloak-client-synced`, then it will contain both mix of synced `admin-client` and `authz-client` stuff. So then we will need another way how to "divide" all those files and which of them should be used only for `admin-client` and which of them only for `authz-client`. This does not seem very practical though?

If we want to clearify a bit more what is synced, maybe we can also rename the directories like `admin-client/src` or `authz-client/src` to something like `src-synced`? This can make it clearer for developers what is synced and should not be touched. WDYT?

TBH My understanding of what @thomasdarimont mentioned yesterday was something different :-) I understood it like this: Some "common" and "core" classes are duplicated in both `admin-client` and `authz-client` modules. For example representation classes or the class `OAuth2Constants` . In theory, this can cause issues if someone uses both `admin-client` and `authz-client` on classpath with different version of both. So we can introduce single module `client-common`, which can have those classes shared to both. Then the `admin-client` and `authz-client` can have dependency on this module. This makes more sense to me. @thomasdarimont can you confirm?

**Comment by thomasdarimont** [comment]
@mposolda yes, your interpretation matches, what I suggested. However, I think this can be combined with "...module or whatever that only contains synced Java files, and a README.md in the top that says don't touch, or some other ways to mention this."
