### ISSUE TITLE
Move most important tests from client package

### ISSUE THREAD

**Issue by graziang** [keycloak/keycloak-client#44]
Move most important tests from  [client package](https://github.com/keycloak/keycloak/tree/main/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/client)

**Comment by mposolda** [comment]
Related issue: https://github.com/keycloak/keycloak/issues/32337 (but that one may be already fixed due some other changes like https://github.com/keycloak/keycloak/commit/e7d9a717c9cf4d3b0089af3618f78efce15b38db )
