### ISSUE TITLE
Remove "release" branches and make sure they are not created during the release

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak-client#86]
For keycloak-client, we may need to maintain only the single `main` branch as the release lifecycle will be always `26.0.x` as long as there are not backwards compatible changes (which hopefully won't be needed for a very long time).

So we don't need the branches like [release/26.0](https://github.com/keycloak/keycloak-client/tree/release/26.0) or [release/alpha](https://github.com/keycloak/keycloak-client/tree/release/alpha) and we can remove them. We can possibly also update GH action release process to not create the branch like `release/26.0` during the release of the client.

**Comment by pskopek** [comment]
Branches release/26.0 and  release/alpha are deleted.

**Comment by pskopek** [comment]
GHA are not creating the release branches automatically.
